{
    "name": "Dashboard App",
    "version": "19.0.1.0.0",
    "summary": "Al-Baha Strategic Office dashboard (white-labelled, dynamic, themeable)",
    "category": "Productivity",
    "author": "Global Solutions",
    "license": "LGPL-3",
    "depends": ["base", "web"],
    "data": [
        "security/ir.model.access.csv",
        "data/theme_data.xml",
        "views/branding_templates.xml",
        "views/login_templates.xml",
        "views/dashboard_action.xml",
        "views/dashboard_page_templates.xml",
        "views/res_users_views.xml",
        "views/res_company_views.xml",
        "data/company_data.xml",
        "data/demo_dashboard.xml",
        "data/dashboard_bindings.xml",
        "data/user_config_data.xml",
        "data/dashboard_edit_access_grant.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "dashboard_app/static/fonts/tajawal.scss",
            "dashboard_app/static/src/login/login.scss",
            "dashboard_app/static/lib/gridstack/gridstack.min.css",
            # the dashboard also runs as a public component on the /dashboard page
            "dashboard_app/static/src/dashboard/dashboard.scss",
            "dashboard_app/static/lib/flatpickr/flatpickr.min.css",
            "dashboard_app/static/lib/gsap/gsap.min.js",
            "dashboard_app/static/lib/gridstack/gridstack-all.js",
            "dashboard_app/static/lib/flatpickr/flatpickr.min.js",
            "dashboard_app/static/lib/flatpickr/ar.min.js",
            "dashboard_app/static/src/dashboard/**/*.js",
            "dashboard_app/static/src/dashboard/**/*.xml",
        ],
        "web.assets_backend": [
            "dashboard_app/static/fonts/tajawal.scss",
            "dashboard_app/static/lib/gridstack/gridstack.min.css",
            "dashboard_app/static/src/dashboard/dashboard.scss",
            "dashboard_app/static/lib/flatpickr/flatpickr.min.css",
            "dashboard_app/static/lib/gsap/gsap.min.js",
            "dashboard_app/static/lib/gridstack/gridstack-all.js",
            "dashboard_app/static/lib/flatpickr/flatpickr.min.js",
            "dashboard_app/static/lib/flatpickr/ar.min.js",
            "dashboard_app/static/src/dashboard/**/*.js",
            "dashboard_app/static/src/dashboard/**/*.xml",
            "dashboard_app/static/src/fields/**/*.scss",
            "dashboard_app/static/src/fields/**/*.js",
        ],
    },
    "post_init_hook": "_set_company_website_logo",
    "installable": True,
    "application": True,
}
